// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/analytics/v1/analytics.proto

package go_url_shortener

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortCode     string                 `protobuf:"bytes,1,opt,name=short_code,json=shortCode,proto3" json:"short_code,omitempty"`
	ClientIp      string                 `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,3,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	AccessedAt    int64                  `protobuf:"varint,4,opt,name=accessed_at,json=accessedAt,proto3" json:"accessed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessLogRequest) Reset() {
	*x = AccessLogRequest{}
	mi := &file_proto_analytics_v1_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessLogRequest) ProtoMessage() {}

func (x *AccessLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_v1_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessLogRequest.ProtoReflect.Descriptor instead.
func (*AccessLogRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_v1_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *AccessLogRequest) GetShortCode() string {
	if x != nil {
		return x.ShortCode
	}
	return ""
}

func (x *AccessLogRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *AccessLogRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *AccessLogRequest) GetAccessedAt() int64 {
	if x != nil {
		return x.AccessedAt
	}
	return 0
}

type AccessLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessLogResponse) Reset() {
	*x = AccessLogResponse{}
	mi := &file_proto_analytics_v1_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessLogResponse) ProtoMessage() {}

func (x *AccessLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_v1_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessLogResponse.ProtoReflect.Descriptor instead.
func (*AccessLogResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_v1_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *AccessLogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_analytics_v1_analytics_proto protoreflect.FileDescriptor

const file_proto_analytics_v1_analytics_proto_rawDesc = "" +
	"\n" +
	"\"proto/analytics/v1/analytics.proto\x12\fanalytics.v1\"\x8e\x01\n" +
	"\x10AccessLogRequest\x12\x1d\n" +
	"\n" +
	"short_code\x18\x01 \x01(\tR\tshortCode\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x03 \x01(\tR\tuserAgent\x12\x1f\n" +
	"\vaccessed_at\x18\x04 \x01(\x03R\n" +
	"accessedAt\"-\n" +
	"\x11AccessLogResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2`\n" +
	"\x10AnalyticsService\x12L\n" +
	"\tLogAccess\x12\x1e.analytics.v1.AccessLogRequest\x1a\x1f.analytics.v1.AccessLogResponseB)Z'github.com/bezzang-dev/go-url-shortenerb\x06proto3"

var (
	file_proto_analytics_v1_analytics_proto_rawDescOnce sync.Once
	file_proto_analytics_v1_analytics_proto_rawDescData []byte
)

func file_proto_analytics_v1_analytics_proto_rawDescGZIP() []byte {
	file_proto_analytics_v1_analytics_proto_rawDescOnce.Do(func() {
		file_proto_analytics_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analytics_v1_analytics_proto_rawDesc), len(file_proto_analytics_v1_analytics_proto_rawDesc)))
	})
	return file_proto_analytics_v1_analytics_proto_rawDescData
}

var file_proto_analytics_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_analytics_v1_analytics_proto_goTypes = []any{
	(*AccessLogRequest)(nil),  // 0: analytics.v1.AccessLogRequest
	(*AccessLogResponse)(nil), // 1: analytics.v1.AccessLogResponse
}
var file_proto_analytics_v1_analytics_proto_depIdxs = []int32{
	0, // 0: analytics.v1.AnalyticsService.LogAccess:input_type -> analytics.v1.AccessLogRequest
	1, // 1: analytics.v1.AnalyticsService.LogAccess:output_type -> analytics.v1.AccessLogResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_analytics_v1_analytics_proto_init() }
func file_proto_analytics_v1_analytics_proto_init() {
	if File_proto_analytics_v1_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analytics_v1_analytics_proto_rawDesc), len(file_proto_analytics_v1_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_v1_analytics_proto_goTypes,
		DependencyIndexes: file_proto_analytics_v1_analytics_proto_depIdxs,
		MessageInfos:      file_proto_analytics_v1_analytics_proto_msgTypes,
	}.Build()
	File_proto_analytics_v1_analytics_proto = out.File
	file_proto_analytics_v1_analytics_proto_goTypes = nil
	file_proto_analytics_v1_analytics_proto_depIdxs = nil
}
